### ISSUE TITLE
Approval Mechanism

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/DefinitelySetup#13]
Implement a mechanism to approve and merge pull requests at the end of each week if the constraint size for the circuit is below 1M. This may involve setting up a continuous integration (CI) system, with scripts that validate and approve the pull requests.

**Comment by ctrlc03** [comment]
Steps:

- [ ] setup GitHub environments (prod/staging/dev)
- [ ] add secrets
- [ ] workflow to setup ceremony based on which branch the code is committed to:
   - [ ] add protection so that only admin can run
- [ ] workflow to check PRs with changes to ./ceremonies and validate that the required files are added 
- [ ] workflow to check PRs with changes to ./ceremonies and validate that the p0tion config is correct and that constraints are < 1MIL
- [ ] scheduled workflow to setup a ceremony from PRs where the constraints are < 1M and that the setup config is valid
